#!/bin/bash
#
# Configure local environment for connecting to remote ComfyUI
# Usage: ./configure-local.sh <runpod-url>
#
# This creates/updates the Claude Code settings file with the ComfyUI URL.
#

set -e

COMFYUI_URL="$1"

if [ -z "$COMFYUI_URL" ]; then
    echo "Usage: $0 <comfyui-url>"
    echo ""
    echo "Example:"
    echo "  $0 https://abc123-8188.proxy.runpod.net"
    echo ""
    exit 1
fi

# Get the directory where this script lives
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MCP_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

echo "ComfyUI MCP Directory: $MCP_DIR"
echo "ComfyUI URL: $COMFYUI_URL"
echo ""

# Test connection first
echo "Testing connection..."
if curl -s --connect-timeout 5 "$COMFYUI_URL" > /dev/null 2>&1; then
    echo "✓ Connection successful"
else
    echo "⚠ Warning: Could not connect to $COMFYUI_URL"
    echo "  Continuing anyway (ComfyUI may not be started yet)"
fi
echo ""

# Create .env file for easy local testing
ENV_FILE="$MCP_DIR/.env"
echo "Creating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# ComfyUI MCP Configuration
# Generated by configure-local.sh on $(date)

COMFYUI_URL=$COMFYUI_URL
COMFYUI_MODEL=
COMFYUI_OUTPUT_DIR=/tmp/comfyui-output
EOF

echo "✓ Created $ENV_FILE"
echo ""

# Output Claude Code config snippet
echo "=========================================="
echo "Claude Code Configuration"
echo "=========================================="
echo ""
echo "Add this to your Claude Code settings:"
echo "(~/.claude/settings.json or .claude/settings.local.json)"
echo ""
echo "{"
echo "  \"mcpServers\": {"
echo "    \"comfyui\": {"
echo "      \"command\": \"node\","
echo "      \"args\": [\"$MCP_DIR/dist/index.js\"],"
echo "      \"env\": {"
echo "        \"COMFYUI_URL\": \"$COMFYUI_URL\","
echo "        \"COMFYUI_MODEL\": \"\","
echo "        \"COMFYUI_OUTPUT_DIR\": \"/tmp/comfyui-output\""
echo "      }"
echo "    }"
echo "  }"
echo "}"
echo ""
echo "=========================================="
echo ""
echo "After updating settings, restart Claude Code."
