#!/usr/bin/env bash
#
# One-Shot Full Deployment Script
#
# Creates everything from scratch:
#   1. Network volume (via Terraform)
#   2. Downloads all models to volume
#   3. Rebuilds Docker image
#   4. Creates serverless endpoint
#
# Usage:
#   ./deploy-all.sh
#
# Environment:
#   RUNPOD_API_KEY - Required (or set in terraform.tfvars)
#   SKIP_DOCKER=1  - Skip Docker build/push
#   SKIP_PROVISION=1 - Skip model downloads (if volume already provisioned)
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$DEPLOY_DIR/terraform"
SERVERLESS_DIR="$DEPLOY_DIR/serverless"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; exit 1; }
info() { echo -e "${BLUE}[i]${NC} $1"; }
step() { echo -e "\n${CYAN}━━━ $1 ━━━${NC}\n"; }

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          ComfyUI Serverless - Full Deployment                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# =============================================================================
# Step 0: Prerequisites
# =============================================================================

step "Step 0: Checking Prerequisites"

command -v tofu >/dev/null 2>&1 || command -v terraform >/dev/null 2>&1 || error "tofu or terraform required"
command -v docker >/dev/null 2>&1 || error "docker required"
command -v jq >/dev/null 2>&1 || error "jq required"

TF_CMD="tofu"
command -v tofu >/dev/null 2>&1 || TF_CMD="terraform"
log "Using: $TF_CMD"

cd "$TERRAFORM_DIR"

# Check for API key
if [[ ! -f terraform.tfvars ]]; then
    error "terraform.tfvars not found. Create it with runpod_api_key and template_id"
fi

log "Prerequisites OK"

# =============================================================================
# Step 1: Create Network Volume (via API - Terraform provider doesn't support it)
# =============================================================================

step "Step 1: Creating Network Volume"

# Get API key from tfvars
RUNPOD_API_KEY=$(grep runpod_api_key terraform.tfvars | cut -d'"' -f2)
VOLUME_NAME="comfyui-models"
VOLUME_SIZE=100
DATACENTER="US-TX-3"

# Check if volume already exists
info "Checking for existing volume..."
EXISTING_VOLUME=$(curl -s -X POST "https://api.runpod.io/graphql" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $RUNPOD_API_KEY" \
    -d '{"query": "query { myself { networkVolumes { id name size } } }"}' \
    | jq -r ".data.myself.networkVolumes[] | select(.name == \"$VOLUME_NAME\") | .id" 2>/dev/null || echo "")

if [[ -n "$EXISTING_VOLUME" && "$EXISTING_VOLUME" != "null" ]]; then
    VOLUME_ID="$EXISTING_VOLUME"
    log "Using existing volume: $VOLUME_ID"
else
    info "Creating new network volume via API..."

    CREATE_RESULT=$(curl -s -X POST "https://api.runpod.io/graphql" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $RUNPOD_API_KEY" \
        -d "{\"query\": \"mutation { createNetworkVolume(input: { name: \\\"$VOLUME_NAME\\\", size: $VOLUME_SIZE, dataCenterId: \\\"$DATACENTER\\\" }) { id name size } }\"}")

    VOLUME_ID=$(echo "$CREATE_RESULT" | jq -r '.data.createNetworkVolume.id // empty')

    if [[ -z "$VOLUME_ID" || "$VOLUME_ID" == "null" ]]; then
        echo "$CREATE_RESULT" | jq .
        error "Failed to create network volume"
    fi

    log "Network volume created: $VOLUME_ID"
fi

# Update terraform.tfvars with volume ID for later use
if ! grep -q "existing_volume_id" terraform.tfvars; then
    echo "" >> terraform.tfvars
    echo "# Auto-generated by deploy-all.sh" >> terraform.tfvars
    echo "create_volume = false" >> terraform.tfvars
    echo "existing_volume_id = \"$VOLUME_ID\"" >> terraform.tfvars
else
    # Update existing value
    sed -i '' "s/existing_volume_id = .*/existing_volume_id = \"$VOLUME_ID\"/" terraform.tfvars
fi

log "Volume ID saved to terraform.tfvars"

# =============================================================================
# Step 2: Provision Models
# =============================================================================

if [[ "${SKIP_PROVISION:-}" != "1" ]]; then
    step "Step 2: Provisioning Models (~30GB, 10-20 min)"

    "$SCRIPT_DIR/provision-volume.sh" "$VOLUME_ID" "$DATACENTER"

    log "Models provisioned"
else
    warn "Skipping provisioning (SKIP_PROVISION=1)"
fi

# =============================================================================
# Step 3: Build and Push Docker Image
# =============================================================================

if [[ "${SKIP_DOCKER:-}" != "1" ]]; then
    step "Step 3: Building Docker Image"

    cd "$SERVERLESS_DIR"

    # Get Docker Hub username from existing image or prompt
    DOCKER_IMAGE="pelekes/comfyui-serverless"

    info "Building $DOCKER_IMAGE:latest"
    docker build -t "$DOCKER_IMAGE:latest" .

    info "Pushing to Docker Hub..."
    docker push "$DOCKER_IMAGE:latest"

    log "Docker image pushed"
    cd "$TERRAFORM_DIR"
else
    warn "Skipping Docker build (SKIP_DOCKER=1)"
fi

# =============================================================================
# Step 4: Create Serverless Endpoint
# =============================================================================

step "Step 4: Creating Serverless Endpoint"

$TF_CMD apply -auto-approve

ENDPOINT_ID=$($TF_CMD output -raw endpoint_id)
ENDPOINT_URL=$($TF_CMD output -raw endpoint_url)

log "Endpoint created: $ENDPOINT_ID"

# =============================================================================
# Step 5: Wake and Test
# =============================================================================

step "Step 5: Testing Endpoint"

# Get API key for testing
RUNPOD_API_KEY=$(grep runpod_api_key terraform.tfvars | cut -d'"' -f2)

info "Sending health check (may take 30-60s for cold start)..."

HEALTH_RESULT=$(curl -s -X POST "${ENDPOINT_URL}/runsync" \
    -H "Authorization: Bearer $RUNPOD_API_KEY" \
    -H "Content-Type: application/json" \
    -d '{"input": {"action": "health"}}' \
    --max-time 120 || echo '{"status": "timeout"}')

echo "$HEALTH_RESULT" | jq .

# =============================================================================
# Done!
# =============================================================================

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    Deployment Complete!                         ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo "║"
echo "║  Endpoint ID:  $ENDPOINT_ID"
echo "║  Endpoint URL: $ENDPOINT_URL"
echo "║  Volume ID:    $VOLUME_ID"
echo "║"
echo "║  Test commands:"
echo "║"
echo "║  # Health check"
echo "║  curl -X POST '${ENDPOINT_URL}/runsync' \\"
echo "║    -H 'Authorization: Bearer \$RUNPOD_API_KEY' \\"
echo "║    -d '{\"input\": {\"action\": \"health\"}}'"
echo "║"
echo "║  # Generate portrait"
echo "║  curl -X POST '${ENDPOINT_URL}/runsync' \\"
echo "║    -H 'Authorization: Bearer \$RUNPOD_API_KEY' \\"
echo "║    -d '{\"input\": {\"action\": \"portrait\", \"description\": \"Viking warrior\"}}'"
echo "║"
echo "║  # Scale down when done"
echo "║  gh workflow run gpu-control.yml -f action=sleep"
echo "║"
echo "╚════════════════════════════════════════════════════════════════╝"
